#!/usr/bin/env python2

# https://python-escpos.readthedocs.io/en/latest/user/raspi.html
# imagemagick

from escpos.printer import Usb
import sys, os
from subprocess import call
import glob

files = glob.glob('/tmp/print*.jpg')
for f in files:
	os.remove(f)

doConvert = False

if sys.argv[1].endswith('.pdf'):
	doConvert = True
#	print("DO CONVERT because {} end with .pdf".format(sys.argv[1]))
else:
	call(['cp', sys.argv[1], "/tmp/print.jpg"])   # Copy image in case convert fails
	from PIL import Image
	im = Image.open(sys.argv[1])
	width, height = im.size
	if width < 576 and not width == 567:
	  doConvert = True

if doConvert:
#	print("convert ..")
	call(["convert", sys.argv[1], "-resize", "576x", "-background", "white", "-alpha", "remove", "/tmp/print.jpg"])
#	print("end !")

p = Usb(0x04b8,0x0e15,0)
files = glob.glob('/tmp/print*.jpg')
print files
for f in files:
	p.image(f)
	if len(sys.argv) > 2 and sys.argv[2] == '1':
		p.cut()

# CUT AT THE END IF NO CUT INBETWEEN
if len(sys.argv) > 3 and sys.argv[2] != '1':
	p.cut()


sys.exit(0)

# sudo apt install python-pip libjpeg8-dev imagemagick
# sudo pip install python-escpos
