#!/usr/bin/env python
from escpos.printer import Usb
import sys
from subprocess import call

call(['rm', "/tmp/print.jpg"])
call(['cp', sys.argv[1], "/tmp/print.jpg"])

if sys.argv[1].endswith('.pdf'):
	print 'converting PDF..'
	call(['montage', '-resize', '576x', '-mode', 'concatenate', '-tile', '1', '-quality', '100', sys.argv[1], "/tmp/print.jpg"])
else:
	#from PIL import Image
	#im = Image.open(sys.argv[1])
	#width, height = im.size
	#if width < 576:
	print 'resizing..'
	call(["convert", sys.argv[1], "-resize", "576x", "/tmp/print.jpg"])
	
sys.exit(0)
p = Usb(0x04b8,0x0e15,0)
p.set(density=2)
p.image("/tmp/print.jpg")
if sys.argv[2] == '1':
    p.cut()
sys.exit(0)

# sudo apt install python-pip libjpeg8-dev imagemagick
# pip install python-escpos
